<template>
	<div class="cartinaCss">
		qui ci metto la cartina!

		<!-- Image Map Generated by http://www.image-map.net/ -->
		<img src="../../assets/IT-EPS-01-0004.png" usemap="#image-map">

		<map name="image-map">
		<area target="" alt="Liguria" title="Liguria" href="" coords="504,431,537,433,561,419,573,396,592,400,614,413,630,417,646,407,621,382,594,364,557,360,520,387" shape="poly"  v-on:mouseover="mouseOver">
			<area target="" alt="Toscana" title="Toscana" href="" coords="625,417,650,402,678,409,708,411,728,436,725,464,716,492,706,513,686,527,649,542,619,518,609,470" shape="poly">
			<area target="" alt="Lazio" title="Lazio" href="" coords="690,529,719,492,744,517,782,501,777,529,771,545,805,564,810,583,797,598,767,616" shape="poly">
		</map>

	</div>


</template>

<script>
	import { mapGetters, mapActions } from 'vuex'
	export default {
		created: function(){
		},
		computed: {
			...mapGetters([
				'loggedUser',
				'isLogged',
				'errorMessage'
				])
		},
		props: {

		},
		components: {
		},
		data: function() {
			return {
				sito : {}
			}
		},
		methods: {
			mouseOver: function(){
	            alert(1)
	        }
		}
	}
	

</script>

<style lang="scss">

	.cartinaCss{
		margin: 0 auto;
		border: 1px solid orange;
		min-width: 400px;
		min-height: 200px;
	}



</style>